[build]
  command = "cd apps/web && rm -rf node_modules && npm install --legacy-peer-deps --include=dev && npx next build"
  publish = "apps/web/.next"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV     = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"